services:
  - type: web
    name: gdsc-2-0-frontend
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 